FROM apache/airflow:2.8.0

USER root
RUN apt-get update \
    && apt-get install -y --no-install-recommends openjdk-17-jre-headless \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64

USER airflow
RUN pip install --no-cache-dir \
    "boto3>=1.34,<2.0" \
    "elasticsearch>=8.0.0,<9.0.0" \
    "pyspark==3.5.0" \
    "redis>=5.0,<6.0" \
    "requests>=2.31,<3.0"
